printWidth = 120
tabWidth = 2
useTabs = false
semi = false
singleQuote = true
trailingComma = "all"
bracketSpacing = false
arrowParens = "avoid"
quoteProps = "as-needed"
endOfLine = "lf"
proseWrap = "preserve"

[[overrides]]
  files = ["**/*.ts"]
  [overrides.options]
    tabWidth = 4
