name: Probby Issue Receiver
description: Create an issue for changes to problem-specs
author: Sascha Mann <git@mail.saschamann.eu>, Derk-Jan Karrenbeld <derk-jan+github@karrenbeld.info>

branding:
  icon: bell
  color: purple

inputs:
  token:
    description: The GH token used to create the issue
    default: ${{ github.token }}
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
