name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - run: npm install

      - name: Verify formatting
        run: npm run format-check
