name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - run: npm install

      - name: Verify formatting
        run: npm run format-check
