name: Tools

on:
  - pull_request_target

jobs:
  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # 4.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true # Remove labels when matching files are reverted or no longer changed by the PR
