name: Tools

on:
  - pull_request_target

jobs:
  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e # 2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true # Remove labels when matching files are reverted or no longer changed by the PR
